<?php

namespace AppBundle\Repository;

/**
 * PlaneModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
